### ISSUE TITLE
User website

### ISSUE THREAD

**Issue by OfficialNexonCraft** [grohsfabian/minecraft-servers-list-lite#2]
No where to add user's website.

**Comment by grohsfabian** [comment]
I will check this too :)

**Comment by grohsfabian** [comment]
Can you be a bit more detailed on what you mean by "user's website" ?

**Comment by OfficialNexonCraft** [comment]
Like adding their Minecraft website not just server.

**Comment by grohsfabian** [comment]
Hello again,

A field for minecraft website won't be added to this version.
