### ISSUE TITLE
No ReCaptcha on Submit form

### ISSUE THREAD

**Issue by OfficialNexonCraft** [grohsfabian/minecraft-servers-list-lite#4]
No ReCaptcha on Submit form

![recaptch](https://cloud.githubusercontent.com/assets/24374915/21073999/64ee3f90-beb3-11e6-91b5-f6227ced98c5.png)

**Comment by wiggles69** [comment]
@NexonCraft looks like this toplist is no compatible with SSL. That's probably why you are missing the recaptcha on submission form.

**Comment by grohsfabian** [comment]
Hello,

If you are using a secure connection, please edit the following code in **pages/submit.php** from 

`<?php echo recaptcha_get_html($settings->public_key); ?>`

to

`<?php echo recaptcha_get_html($settings->public_key, null, true); ?>`

**Comment by OfficialNexonCraft** [comment]
Thanks, it works but now still not can't getting new members in database. Here is the website and try to make a test account. https://www.lyrocis.biz

**Comment by grohsfabian** [comment]
Hello,

Can you please make a new issue and tell me exactly what the problem is ?

Regards,

Fabian.
