### ISSUE TITLE
New released

### ISSUE THREAD

**Issue by OfficialNexonCraft** [grohsfabian/minecraft-servers-list-lite#5]
Your new released 4 days ago, we can submit the server but is not going to the database.

![database](https://cloud.githubusercontent.com/assets/24374915/21186287/9eefb768-c1d9-11e6-8d56-80218a91084d.png)

**Comment by grohsfabian** [comment]
Hello,

I will check this :)

**Comment by wiggles69** [comment]
Any updates on this?

**Comment by OfficialNexonCraft** [comment]
This is a free list so it will take awhile for support.

**Comment by grohsfabian** [comment]
Hello again,

Sorry to keep you guys waiting. I will start working on updating it today!

**Comment by grohsfabian** [comment]
Submitted an update, working now!
