### ISSUE TITLE
Update 1.0.3

### ISSUE THREAD

**Issue by wiggles69** [grohsfabian/minecraft-servers-list-lite#6]
I've been messing with the new update but I noticed admin can only be the one that can add to the new servers list category. When a visitor tries to add a server, submission will work but not added to the New Server List category. When the admin tries to find the server, it won't be found. When admin adds a server, it will show on the new server list category even if it's not activated. So I'm safe to say error is still there on submitting a server.

**Comment by grohsfabian** [comment]
Hello,

Can you please replace the **pages/submit.php** with the new one that I've commited and test it out ? I'm not on my work laptop right now. Let me know if it works 👍 

Regards,

Fabian.

**Comment by wiggles69** [comment]
Awesome, works now thanks.
