### ISSUE TITLE
reCaptcha Not working

### ISSUE THREAD

**Issue by funkystudios** [grohsfabian/minecraft-servers-list-lite#8]
Hey,

reCaptcha isn't working for me. It's displayed, however every time I put in the right response, it keeps saying "Captcha not valid !" and the server isn't submitted.

My site has an SSL certificate, so I replaced that one line with this <?php echo recaptcha_get_html($settings->public_key, null, true); ?> but it didn't work.

If possible could you consider adding support for reCaptcha v2?

Thank you

**Comment by grohsfabian** [comment]
Hello,

That fix should be working if you are using a ssl website. I will try to submit a quick update for this script too :). Meanwhile you can check out the premium version here -> https://codecanyon.net/item/minecraft-servers-list/4062368 

Regards,

Fabian.
